### ISSUE TITLE
Unclear how to add comments when not logged in

### ISSUE THREAD

**Issue by exerro** [Xella37/PineStore-site#6]
This is more of a feature request than a problem. When you're not logged in, there's no indication that it's possible to add comments. I think a `<a href>Log in</a> to add your comments` label would help people new to the site to engage more and also help convey the benefits of logging in.

**Comment by Xella37** [comment]
Good suggestion!

**Comment by Xella37** [comment]
Added with 7244bb8e631f553bec7e99c3607e4f67deaaaa61 :3
